CanTeleport = {
 {
  ["Sky3"] = Vector3.new(-7894, 5547, -380),
  ["Sky3Exit"] = Vector3.new(-4607, 874, -1667),
  ["UnderWater"] = Vector3.new(61163, 11, 1819),
  ["UnderwaterExit"] = Vector3.new(3864, 6, -1926),
 },
 {
  ["Swan Mansion"] = Vector3.new(-390, 332, 673),
  ["Swan Room"] = Vector3.new(2285, 15, 905),
  ["Cursed Ship"] = Vector3.new(923, 126, 32852),
 },
 {
  ["Floating Turtle"] = Vector3.new(-12462, 375, -7552),
  ["Hydra Island"] = Vector3.new(5745, 610, -267),
  ["Mansion"] = Vector3.new(-12462, 375, -7552),
  ["Castle"] = Vector3.new(-5036, 315, -3179),
 }
}
Step = {Vector3.new(0, 60, 0),Vector3.new(0, 0, 60),Vector3.new(0, 0, -60),Vector3.new(60, 0, 0),Vector3.new(-60, 0, 0),}
